### ISSUE TITLE
Additional data types support

### ISSUE THREAD

**Issue by jaclas** [Xor-el/SimpleBaseLib4Pascal#1]
```
IBaseXX = interface(IInterface)
    function Encode(const bytes: TSimpleBaseLibByteArray; padding: Boolean): String;
    function Decode(const text: String): TSimpleBaseLibByteArray;
end;
```

Is possible to extend interfaces to Encode/Decode additional data types like Pointer?

Eg.
function Encode(const memory : Pointer; size : Integer; padding : Boolean) : string;

**Comment by Xor-el** [comment]
@jaclas , while it is technically possible, I feel it will end up cluttering the whole interface and goal of the library which was meant to be as simple as possible.
But you can simply move the contents the pointer points to,  to a byte array or string respectively before passing it to the library.

**Comment by jaclas** [comment]
Yes, I know that I can copy and move data, but imho... the name "Simple" suggests simple use of the library, not the simplicity of the code in the library :-)

See how I must now "tinkering":

```
// aPointer is a pointer to ansi string (one byte)
function DecodeMemoryToRawByteString(aMemory: Pointer; const aSize: Integer): RawByteString;
var
  lStr: RawByteString;
  lBytes: TBytes;
begin
  SetLength(lStr, aSize);   <-- **allocating aSizeBytes**
  Move(aMemory^, lStr[1], aSize);
  lBytes := TBase32.Crockford.Decode(lStr); <-- **allocating Base32 size of input data**
  SetLength(Result, Length(lBytes)); <-- **allocating Base32 size of input data**
  Move(lBytes[0], Result[1], Length(lBytes));
end;  
```

Three allocations and two copying data, it is very inefficient :-(

**Comment by Xor-el** [comment]
@jaclas , adding this feature will result to more unnecessary complexity in this library and increase the possibility of mistakes/misuse by inexperienced end users so I am closing this issue.
if you feel the need to debate further on this with more convincing points, please do not hesitate to reopen this issue.
Thanks.
