### ISSUE TITLE
[DCC Fatal Error] F2084 Internal Error: AV07F3F897-R1A9FFE9C-0

### ISSUE THREAD

**Issue by Uefi1** [Xor-el/SimpleBaseLib4Pascal#2]
Hi, I am getting a compilation error [DCC Fatal Error] F2084 Internal Error: AV07F3F897-R1A9FFE9C-0 
Delphi XE2

**Comment by Xor-el** [comment]
Hello,  this is an internal compiler error that could come from a couple of issues. 
Could be the use of inline or generics/generic arrays, usage of static or something as simple as using open arrays as arguments.
Unfortunately I don't have access to XE2 to test.
At the moment,  I only have access to Delphi 10.4 and this builds and runs ok there.
One quick question,  are you using the latest update of XE2 as I encountered some issues while testing with XE2 in the past and installing the latest XE2 update fixed the problem.

**Comment by Uefi1** [comment]
Hello yes I am using the latest update Delphi XE2 UPDATE 4 forgot to say first writes [DCC Fatal Error] SbpBase32Alphabet.pas(119): F2084 Internal Error: URW1147 after some time if something is poke in the code [DCC Fatal Error] F2084 Internal Error: AV07F3F897-R1A9FFE9C-0
Error falls on SbpBase32Alphabet.pas !

In general, I catch the same error in all three components:
1. HashLib4Pascal the old version from the fork, by the way, compiles fine 
2. CryptoLib4Pascal
3. SimpleBaseLib4Pascal

**Comment by Uefi1** [comment]
This fork HashLib4Pascal compiles just fine:
https://github.com/vincentsoft/HashLib4Pascal
And SimpleBaseLib4 Pascal doesn't even compile forks (

Try downloading a pirated version of Delphi XE2 or a portable one at the time of fix
Please fix it is very important!

**Comment by Xor-el** [comment]
@Uefi1 , the branch you mentioned is very old, about 282 commits behind.
When I started out the project, I had access to XE2 (from work) so I could test against it.
unfortunately I have no access to that anymore.
I would suggest you upgrade your Delphi version to something modern say 10.4 or higher (as that is the only version I have access to at the moment).
I also don't have the zeal or ability to support older Delphi versions as they have a lot of internal compiler bugs.
that been said, even if I wanted to support XE2, using a pirated version is not a route I would want to take.

lastly, the error you are getting seems to point to the compiler inability to perform inlining in some of those methods.
here is what I suggest you do, comment out the `inline;` qualifier in front of those methods and try again.

**Comment by Uefi1** [comment]
Hail, comment inline; did not help =( are there any other options ?

`unit SbpBase32Alphabet;

{$I ..\Include\SimpleBaseLib.inc}

interface

uses
  SysUtils,
  SbpUtilities,
  SbpEncodingAlphabet,
  SbpSimpleBaseLibTypes,
  SbpIBase32Alphabet;

type
  TBase32Alphabet = class(TEncodingAlphabet, IBase32Alphabet)

  strict private

    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;

    procedure MapAlternate(source, destination: Char); // inline;
    procedure MapLowerCaseCounterParts(const alphabet: String); // inline;

    class function GetCrockford: IBase32Alphabet; static; // inline;
    class function GetRfc4648: IBase32Alphabet; static; // inline;
    class function GetExtendedHex: IBase32Alphabet; static; // inline;

    class constructor Base32Alphabet();

  public
    class property Crockford: IBase32Alphabet read GetCrockford;
    class property Rfc4648: IBase32Alphabet read GetRfc4648;
    class property ExtendedHex: IBase32Alphabet read GetExtendedHex;
    constructor Create(const alphabet: String);
    constructor CreateCrockford();
    destructor Destroy; override;
  end;`

**Comment by Xor-el** [comment]
can you try commenting out the `static;` too.

**Comment by Uefi1** [comment]
Tried to swear at [DCC Fatal Error] F2063 Could not compile used unit 'SbpBase32Alphabet.pas'


`    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;

    procedure MapAlternate(source, destination: Char); //inline;
    procedure MapLowerCaseCounterParts(const alphabet: String); //inline;

    class function GetCrockford: IBase32Alphabet; //static; inline;
    class function GetRfc4648: IBase32Alphabet; //static; inline;
    class function GetExtendedHex: IBase32Alphabet; //static; inline;

    class constructor Base32Alphabet();

`

**Comment by Xor-el** [comment]
I sincerely have no idea what next to suggest.

**Comment by Uefi1** [comment]
> I sincerely have no idea what next to suggest.

I read somewhere that it's a mistake F2084 Internal Error: URW1147 can occur if the class is somehow incorrectly declared
Could this be helpful in solving the problem:
https://www.generacodice.com/ru/articolo/41771?titolo=How-to-solve-Delphi%27s-%5BPascal-Fatal-Error%5D-F2084-Internal-Error%3A-LA33

**Comment by Xor-el** [comment]
actually, a lot of things can cause that error, in the past using `inline`,  `static` and also `strict private` instead of `private` can cause it.
so we have ruled out `inline`, `static`. can you use `private` instead of `strict private` in that class.

**Comment by Uefi1** [comment]
I don't really understand how to write all this programmatically, can you help?)

**Comment by Xor-el** [comment]
on https://github.com/Xor-el/SimpleBaseLib4Pascal/blob/master/SimpleBaseLib/src/Bases/SbpBase32Alphabet.pas#L17
replace `strict private` with `private`

**Comment by Uefi1** [comment]
I have tried this for a long time =) Can we somehow contact in a telegram for example?

**Comment by Xor-el** [comment]
hmmm, only thing I can suggest now is that you upgrade your Delphi version.
reason is I am certain you will probably need to use `CryptoLib4Pascal` in the future and that library has never supported XE2 before. infact support for that library started at Delphi Tokyo.
My honest advice is that you upgrade to 10.4 or later.

**Comment by Uefi1** [comment]
> My honest advice is that you upgrade to 10.4 or later.

I can't do it on my own =(
You need to somehow compile under XE2

**Comment by Uefi1** [comment]
I removed some functions and procedures so it really compiles, for example, the matter is somewhere in them:
`unit SbpBase32Alphabet;

{$I ..\Include\SimpleBaseLib.inc}

interface

uses
  SysUtils,
  SbpUtilities,
  SbpEncodingAlphabet,
  SbpSimpleBaseLibTypes,
  SbpIBase32Alphabet;

type
  TBase32Alphabet = class(TEncodingAlphabet, IBase32Alphabet)

  strict private

    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;



  public

    constructor Create(const alphabet: String);
    constructor CreateCrockford();
    destructor Destroy; override;
  end;

implementation

{ TBase32Alphabet }




constructor TBase32Alphabet.Create(const alphabet: String);
begin
  Inherited Create(32, alphabet);
  //MapLowerCaseCounterParts(alphabet);
end;

constructor TBase32Alphabet.CreateCrockford();
begin
  Create('0123456789ABCDEFGHJKMNPQRSTVWXYZ');
  //MapAlternate('O', '0');
  //MapAlternate('I', '1');
  //MapAlternate('L', '1');
end;

destructor TBase32Alphabet.Destroy;
begin
  inherited Destroy;
end;


end.`

**Comment by Xor-el** [comment]
so you say commenting out 
```
    procedure MapAlternate(source, destination: Char); inline;
    procedure MapLowerCaseCounterParts(const alphabet: String); inline;
```

allows it compile?

**Comment by Uefi1** [comment]
> allows it compile?

I just figured out that it was the procedures, commenting on them, I compiled a package:

`unit SbpBase32Alphabet;

{$I ..\Include\SimpleBaseLib.inc}

interface

uses
  SysUtils,
  SbpUtilities,
  SbpEncodingAlphabet,
  SbpSimpleBaseLibTypes,
  SbpIBase32Alphabet;

type
  TBase32Alphabet = class(TEncodingAlphabet, IBase32Alphabet)

  strict private

    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;

    //procedure MapAlternate(source, destination: Char); inline;
    //procedure MapLowerCaseCounterParts(const alphabet: String); inline;

    class function GetCrockford: IBase32Alphabet; static; inline;
    class function GetRfc4648: IBase32Alphabet; static; inline;
    class function GetExtendedHex: IBase32Alphabet; static; inline;

    class constructor Base32Alphabet();

  public
    class property Crockford: IBase32Alphabet read GetCrockford;
    class property Rfc4648: IBase32Alphabet read GetRfc4648;
    class property ExtendedHex: IBase32Alphabet read GetExtendedHex;
    constructor Create(const alphabet: String);
    constructor CreateCrockford();
    destructor Destroy; override;
  end;

implementation

{ TBase32Alphabet }

{procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin
  result := ReverseLookupTable[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;}

//procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
//var
//  LowPoint, HighPoint, I: Int32;
//  c: Char;
//begin
//{$IFDEF DELPHIXE3_UP}
//  LowPoint := System.Low(alphabet);
//  HighPoint := System.High(alphabet);
//{$ELSE}
//  LowPoint := 1;
//  HighPoint := System.Length(alphabet);
//{$ENDIF DELPHIXE3_UP}
//  for I := LowPoint to HighPoint do
//  begin
//    c := alphabet[I];
//    if TUtilities.IsUpper(c) then
//    begin
//      Map(TUtilities.LowCase(c), ReverseLookupTable[Ord(c)] - 1);
//    end;
//  end;
//end;

class constructor TBase32Alphabet.Base32Alphabet;
begin
  FCrockford := TBase32Alphabet.CreateCrockford();
  FRfc4648 := TBase32Alphabet.Create('ABCDEFGHIJKLMNOPQRSTUVWXYZ234567');
  FExtendedHex := TBase32Alphabet.Create('0123456789ABCDEFGHIJKLMNOPQRSTUV');
end;

constructor TBase32Alphabet.Create(const alphabet: String);
begin
  Inherited Create(32, alphabet);
  //MapLowerCaseCounterParts(alphabet);
end;

constructor TBase32Alphabet.CreateCrockford();
begin
  Create('0123456789ABCDEFGHJKMNPQRSTVWXYZ');
  //MapAlternate('O', '0');
  //MapAlternate('I', '1');
  //MapAlternate('L', '1');
end;

destructor TBase32Alphabet.Destroy;
begin
  inherited Destroy;
end;

class function TBase32Alphabet.GetCrockford: IBase32Alphabet;
begin
  result := TBase32Alphabet.CreateCrockford();
end;

class function TBase32Alphabet.GetExtendedHex: IBase32Alphabet;
begin
  result := FExtendedHex;
end;

class function TBase32Alphabet.GetRfc4648: IBase32Alphabet;
begin
  result := FRfc4648;
end;

end.
`

**Comment by Xor-el** [comment]
but those procedures you commented out are needed for proper functioning.

**Comment by Xor-el** [comment]
can you undo your changes then replace
`procedure MapLowerCaseCounterParts(const alphabet: String); inline;`
with
`procedure MapLowerCaseCounterParts(alphabet: String); inline;`

and 
`procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);`
with
`procedure TBase32Alphabet.MapLowerCaseCounterParts(alphabet: String);`

**Comment by Uefi1** [comment]
> can you undo your changes then replace

This is how it worked:
`type
  TBase32Alphabet = class(TEncodingAlphabet, IBase32Alphabet)

  strict private

    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;

    class procedure MapAlternate(source, destination: Char); inline;
    class procedure MapLowerCaseCounterParts(const alphabet: String); inline;

    class function GetCrockford: IBase32Alphabet; static; inline;
    class function GetRfc4648: IBase32Alphabet; static; inline;
    class function GetExtendedHex: IBase32Alphabet; static; inline;

    class constructor Base32Alphabet();

  public
    class property Crockford: IBase32Alphabet read GetCrockford;
    class property Rfc4648: IBase32Alphabet read GetRfc4648;
    class property ExtendedHex: IBase32Alphabet read GetExtendedHex;
    constructor Create(const alphabet: String);
    constructor CreateCrockford();
    destructor Destroy; override;
  end;`

Only now the error is in these lines which I have commented out:

[DCC Error] SbpBase32Alphabet.pas(49): E2233 Property 'ReverseLookupTable' inaccessible here
[DCC Error] SbpBase32Alphabet.pas(51): E2076 This form of method call only allowed for class methods

`class procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin
  //result := ReverseLookupTable[Ord(destination)] - 1;
  //Map(source, result);
  //Map(TUtilities.LowCase(source), result);
end;

class procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
var
  LowPoint, HighPoint, I: Int32;
  c: Char;
begin
{$IFDEF DELPHIXE3_UP}
  LowPoint := System.Low(alphabet);
  HighPoint := System.High(alphabet);
{$ELSE}
  LowPoint := 1;
  HighPoint := System.Length(alphabet);
{$ENDIF DELPHIXE3_UP}
  for I := LowPoint to HighPoint do
  begin
    c := alphabet[I];
    if TUtilities.IsUpper(c) then
    begin
      //Map(TUtilities.LowCase(c), ReverseLookupTable[Ord(c)] - 1);
    end;
  end;`

**Comment by Xor-el** [comment]
go to https://github.com/Xor-el/SimpleBaseLib4Pascal/blob/master/SimpleBaseLib/src/Bases/SbpEncodingAlphabet.pas#L36

replace `strict protected` with `protected`

**Comment by Uefi1** [comment]
> replace `strict protected` with `protected`

Didn't help either:
[DCC Error] SbpBase32Alphabet.pas(49): E2233 Property 'ReverseLookupTable' inaccessible here

**Comment by Xor-el** [comment]
ohh, the error is right.
you cannot access a class instance variable in a static method.
```
class procedure MapAlternate(source, destination: Char); inline;
class procedure MapLowerCaseCounterParts(const alphabet: String); inline;
```

both methods above are meant to be instance methods not static.

revert your changes and replace
`class procedure MapLowerCaseCounterParts(const alphabet: String); inline;`
with
`class procedure MapLowerCaseCounterParts(alphabet: String); inline;`

do similar in the implementation side.

**Comment by Uefi1** [comment]
All removed const in SbpBase32Alphabet.pas and SbpEncodingAlphabet.pas and still an error ((

**Comment by Xor-el** [comment]
which error do you get after removing `const`?

**Comment by Uefi1** [comment]
> which error do you get after removing `const`?

[DCC Error] SbpBase32Alphabet.pas(49): E2233 Property 'ReverseLookupTable' inaccessible here

**Comment by Xor-el** [comment]
did you revert your changes in the procedure as I indicated?
this should be changed to
```
class procedure MapAlternate(source, destination: Char); inline;
class procedure MapLowerCaseCounterParts(const alphabet: String); inline;
```
to
```
procedure MapAlternate(source, destination: Char); inline;
procedure MapLowerCaseCounterParts(alphabet: String); inline;
```

**Comment by Uefi1** [comment]
If I replace class procedure MapAlternate(source, destination: Char); inline; with procedure MapAlternate(source, destination: Char); inline; then comes back again [DCC Fatal Error] SbpBase32Alphabet.pas(120): F2084 Internal Error: URW1147

**Comment by Xor-el** [comment]
replace the implementation of `MapAlternate` and `MapLowerCaseCounterParts` with this below then try to compile

```
procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin

end;

procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
var
  LowPoint, HighPoint, I: Int32;
  c: Char;
begin

end;
```

**Comment by Uefi1** [comment]
> eplace the implementation of `MapAlternate` and `MapLowerCaseCounterParts` with this below then try to compile

Yes it works the package compiles !

`unit SbpBase32Alphabet;

{$I ..\Include\SimpleBaseLib.inc}

interface

uses
  SysUtils,
  SbpUtilities,
  SbpEncodingAlphabet,
  SbpSimpleBaseLibTypes,
  SbpIBase32Alphabet;

type
  TBase32Alphabet = class(TEncodingAlphabet, IBase32Alphabet)

   protected

    class var

      FCrockford, FRfc4648, FExtendedHex: IBase32Alphabet;

    procedure MapAlternate(source, destination: Char); inline;
    procedure MapLowerCaseCounterParts(const alphabet: String); inline;

    class function GetCrockford: IBase32Alphabet; static; inline;
    class function GetRfc4648: IBase32Alphabet; static; inline;
    class function GetExtendedHex: IBase32Alphabet; static; inline;

    class constructor Base32Alphabet();

  public
    class property Crockford: IBase32Alphabet read GetCrockford;
    class property Rfc4648: IBase32Alphabet read GetRfc4648;
    class property ExtendedHex: IBase32Alphabet read GetExtendedHex;
    constructor Create(alphabet: String);
    constructor CreateCrockford();
    destructor Destroy; override;
  end;

implementation

{ TBase32Alphabet }

procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin
//
end;

procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
var
  LowPoint, HighPoint, I: Int32;
  c: Char;
begin
//
end;`

**Comment by Xor-el** [comment]
for `MapAlternate`, can you replace the existing implementation with

```
procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin
  result := ReverseLookupTable[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;
```

and try to compile.

still leave `MapLowerCaseCounterParts `empty

**Comment by Uefi1** [comment]
Yes, if I add code to the error:
[DCC Fatal Error] SbpBase32Alphabet.pas(110): F2084 Internal Error: URW1147
If I leave it empty, then the package is collected
even this is how it works:
procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
begin
  //result := ReverseLookupTable[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;

Obvious error on this line:
result := ReverseLookupTable[Ord(destination)] - 1; // F2084 Internal Error: URW1147

**Comment by Xor-el** [comment]
so it looks like older Delphi version is having issues accessing ReverseLookupTable index value as a property.

replace your existing MapAlternate method with this

```
procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
  tmp: TSimpleBaseLibByteArray;
begin
  tmp := ReverseLookupTable;
  result := tmp[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;
```

**Comment by Uefi1** [comment]
> replace your existing MapAlternate method with this

It's back again:
[DCC Fatal Error] SbpBase32Alphabet.pas(122): F2084 Internal Error: URW1147

This is work how the package is compiled:

`procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
  tmp: TSimpleBaseLibByteArray;
begin
  //tmp := ReverseLookupTable;
  result := tmp[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;

procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
var
  LowPoint, HighPoint, I: Int32;
  c: Char;
begin
{$IFDEF DELPHIXE3_UP}
  LowPoint := System.Low(alphabet);
  HighPoint := System.High(alphabet);
{$ELSE}
  LowPoint := 1;
  HighPoint := System.Length(alphabet);
{$ENDIF DELPHIXE3_UP}
  for I := LowPoint to HighPoint do
  begin
    c := alphabet[I];
    if TUtilities.IsUpper(c) then
    begin
      //Map(TUtilities.LowCase(c), ReverseLookupTable[Ord(c)] - 1);
    end;
  end;
end;`

UPD:
var result: Byte; this is System.Byte from unit System.pas ????

**Comment by Xor-el** [comment]
leave implementation of MapLowerCaseCounterParts empty.
and yes, Byte is System.Byte from System.pas;

only update MapAlternate like I said

```
procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
  tmp: TSimpleBaseLibByteArray;
begin
  tmp := ReverseLookupTable;
  result := tmp[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;
```

test and confirm if this builds

**Comment by Uefi1** [comment]
> test and confirm if this builds

`procedure TBase32Alphabet.MapAlternate(source, destination: Char);
var
  result: Byte;
  tmp: TSimpleBaseLibByteArray;
begin
  tmp := ReverseLookupTable;
  result := tmp[Ord(destination)] - 1;
  Map(source, result);
  Map(TUtilities.LowCase(source), result);
end;

procedure TBase32Alphabet.MapLowerCaseCounterParts(const alphabet: String);
var
  LowPoint, HighPoint, I: Int32;
  c: Char;
begin
//
end;`

F2084 Internal Error: URW1147

**Comment by Xor-el** [comment]
Ok, can you please go to https://github.com/Xor-el/SimpleBaseLib4Pascal/blob/master/SimpleBaseLib/src/Bases/SbpEncodingAlphabet.pas#L44 and remove the `inline;`

**Comment by Uefi1** [comment]
> Ok, can you please go to

Oh yes, I successfully compiled a package of everything for this reason =) Now we need to look towards HashLib4Pascal
Thank you very much !

**Comment by Xor-el** [comment]
you are welcome.
